### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by smscoder-7**

### CODE REVIEW

**Comment by pratik9315** [comment]
Hey there. 
No need to enclose the content in > * format. It is usually used for a note section. Just keep the format as before

**Comment by smscoder-7** [comment]
@pratik2315  ok, let me change

**Comment by smscoder-7** [comment]
@pratik2315  changed, please check & merge

**Comment by pratik9315** [comment]
Hey @smscoder-7! Great work! I have merged the pr. Please check on your hacktoberfest profile if the pr is displayed. Earlier there were some issues i had to resolve.

**Comment by smscoder-7** [comment]
@pratik2315  sure,will check. Thank you!

**Pull request merged**
